// 定義一個包含所有龍刻資料的陣列
const crafts = [
  {
    name: "旋殺陀螺",
    num: "7244",
    shape: "龍印",
    attribute: "dark",
    race: "fairy",
    set: "none",
    acquire: "十三期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "進場CD-2\n消妖_自攻1.5倍\n消20粒_自攻1.15倍",
    leader: ""
  },
  {
    name: "心念娃娃",
    num: "7243",
    shape: "龍符",
    attribute: "fire",
    race: "god",
    set: "none",
    acquire: "十二期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "進場CD-1\n消4連心回1.5倍隊回的血\n消神_神攻1.15倍",
    leader: ""
  },
  {
    name: "獠牙吊飾",
    num: "7177",
    shape: "龍印",
    attribute: "light",
    race: "beast",
    set: "none",
    acquire: "十一期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "延1秒\n開技_自攻1.5倍\n消獸_自攻1.3倍",
    leader: ""
  },
  {
    name: "虎頭機盾",
    num: "7176",
    shape: "龍紋",
    attribute: "light",
    race: "machine",
    set: "none",
    acquire: "十期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "延1秒\n進場CD-2\n消20粒_自攻1.25倍",
    leader: ""
  },
  {
    name: "追龍刀",
    num: "7147",
    shape: "龍印",
    attribute: "wood",
    race: "dragon",
    set: "none",
    acquire: "通過「影子中的龍牙」戰慄級 5 次",
    accumulate: "消除任何符石",
    ability: "5/5/0",
    skill: "進場CD-2\n開技_自攻1.8倍",
    leader: ""
  },
  {
    name: "神寵笠帽",
    num: "7149",
    shape: "龍紋",
    attribute: "fire",
    race: "beast",
    set: "none",
    acquire: "九期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "進場CD-2\n開技_自攻1.5倍\n消獸_自攻1.3倍",
    leader: ""
  },
  {
    name: "靈感羽筆",
    num: "7148",
    shape: "龍紋",
    attribute: "wood",
    race: "human",
    set: "none",
    acquire: "八期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "進場CD-2\n消六種符石_自攻1.5倍\n對水目標_自攻1.2倍",
    leader: ""
  },
  {
    name: "龍顱邪冠 ",
    num: "7137",
    shape: "龍咒",
    attribute: "wood",
    race: "dragon",
    set: "none",
    acquire: "七期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "減傷10%\n消龍_自攻1.5倍\n開技_自攻1.5倍",
    leader: ""
  },
  {
    name: "獵血戰鐮",
    num: "7139",
    shape: "龍紋",
    attribute: "dark",
    race: "beast",
    set: "none",
    acquire: "挑戰「沾染赤血的獸爪」討伐戰 15 次",
    accumulate: "消除任何符石",
    ability: "0/5/5",
    skill: "進場CD-2\n開技_自攻1.8倍",
    leader: ""
  },
  {
    name: "震擊板手",
    num: "7138",
    shape: "龍紋",
    attribute: "wood",
    race: "machine",
    set: "none",
    acquire: "通過「殲滅的電火並射」戰慄級 5 次",
    accumulate: "消除木符石",
    ability: "5/0/5",
    skill: "消25粒_自攻1.2倍\n開技_自攻1.5倍",
    leader: ""
  },
  {
    name: "花語茶壺",
    num: "7136",
    shape: "龍符",
    attribute: "light",
    race: "fairy",
    set: "none",
    acquire: "六期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "進場CD-1\n消妖_自攻1.5倍\n消25粒_自攻1.2倍",
    leader: ""
  },
  {
    name: "聚螢青燈",
    num: "7114",
    shape: "龍丸",
    attribute: "wood",
    race: "fairy",
    set: "none",
    acquire: "五期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "必延1秒\n消妖_自攻1.5倍\n消20粒_自攻1.15倍",
    leader: ""
  },
  {
    name: "燭天熾拳",
    num: "7113",
    shape: "龍璃",
    attribute: "fire",
    race: "human",
    set: "none",
    acquire: "四期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "必延1秒\n進場CD-1\n自身攻擊無視敵防",
    leader: ""
  },
  {
    name: "飛雷戰銃",
    num: "7111",
    shape: "龍璃",
    attribute: "light",
    race: "fairy",
    set: "none",
    acquire: "通過「縱橫於天際之間」戰慄級 5 次",
    accumulate: "消除任何符石",
    ability: "5/0/5",
    skill: "消妖_自攻1.2倍\n消5連心_自攻1.15倍",
    leader: ""
  },
  {
    name: "噬靈巨鐮",
    num: "7100",
    shape: "龍符",
    attribute: "water",
    race: "beast",
    set: "none",
    acquire: "三期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "進場CD-2\n開技_自攻1.5倍\n消獸_自攻1.3倍",
    leader: ""
  },
  {
    name: "異魔血爪",
    num: "7112",
    shape: "龍符",
    attribute: "fire",
    race: "demon",
    set: "none",
    acquire: "挑戰「遮蓋天地的魔翼」討伐戰 15 次",
    accumulate: "連擊 4 或以上",
    ability: "0/5/5",
    skill: "延1.5秒\n消5連火_自攻1.3倍",
    leader: ""
  },
  {
    name: "澄麗雙劍",
    num: "7099",
    shape: "龍咒",
    attribute: "light",
    race: "human",
    set: "none",
    acquire: "二期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "必延1秒\n進場CD-1\n消水光_自攻1.5倍",
    leader: ""
  },
  {
    name: "花鳥藤籃",
    num: "7098",
    shape: "龍印",
    attribute: "dark",
    race: "human",
    set: "none",
    acquire: "首期「戰鬥通行證」豪華獎勵",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "進場CD-1\n每回合回復6000生命力\n消暗心_自攻1.2倍",
    leader: ""
  },
  {
    name: "青羽琴弓",
    num: "7097",
    shape: "龍咒",
    attribute: "wood",
    race: "human",
    set: "none",
    acquire: "挑戰「掌控時局的貴公子」討伐戰 15 次",
    accumulate: "消除木符石",
    ability: "0/5/5",
    skill: "進場CD-2\n消20粒_自攻1.15倍",
    leader: ""
  },
  {
    name: "鴉首棋",
    num: "7089",
    shape: "龍紋",
    attribute: "light",
    race: "demon",
    set: "none",
    acquire: "挑戰「來一局高塔攻防戰」討伐戰 15 次",
    accumulate: "連擊 4 或以上",
    ability: "0/5/5",
    skill: "延1.5秒\n消5連光_自攻1.3倍",
    leader: ""
  },
  {
    name: "浮生蓮",
    num: "7090",
    shape: "龍符",
    attribute: "light",
    race: "beast",
    set: "none",
    acquire: "通過「識別是非亦識諸味」戰慄級 5 次",
    accumulate: "消除任何符石",
    ability: "5/0/5",
    skill: "進場CD-2\n開技_自攻1.5倍",
    leader: ""
  },
  {
    name: "凶蛇杖",
    num: "7067",
    shape: "龍刃",
    attribute: "wood",
    race: "god",
    set: "none",
    acquire: "挑戰「萬蛇出動」討伐戰 15 次",
    accumulate: "消除任何符石",
    ability: "0/5/5",
    skill: "進場CD-1\n進場CD-1",
    leader: ""
  },
  {
    name: "融魂燭",
    num: "7066",
    shape: "龍印",
    attribute: "dark",
    race: "fairy",
    set: "none",
    acquire: "挑戰「喜好移動屍體的怪癖」討伐戰 15 次",
    accumulate: "消除心符石",
    ability: "0/5/5",
    skill: "消妖_自攻1.2倍\n消5連心_自攻1.15倍",
    leader: ""
  },
  {
    name: "魔稜鏡",
    num: "7057",
    shape: "龍咒",
    attribute: "light",
    race: "beast",
    set: "none",
    acquire: "挑戰「於大世界中覓道救眾」討伐戰 15 次",
    accumulate: "消除任何符石",
    ability: "5/5/0",
    skill: "延1.5秒\n消獸_自攻1.3倍",
    leader: ""
  },
  {
    name: "伐雪斧",
    num: "7058",
    shape: "龍咒",
    attribute: "dark",
    race: "beast",
    set: "none",
    acquire: "通過「拯救迷路者的善獸」戰慄級 5 次",
    accumulate: "消除任何符石",
    ability: "5/5/0",
    skill: "延1.5秒\n消獸_自攻1.3倍",
    leader: ""
  },
  {
    name: "星河話筒",
    num: "4263-4269",
    shape: "-",
    attribute: "none",
    race: "none",
    set: "novaH",
    acquire: "「聖誕冬祭」道具收集任務",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "進場CD-3\n消20粒_自攻1.15倍\n開技_自攻1.5倍",
    leader: ""
  },
  {
    name: "虹彩話筒",
    num: "4109-4115",
    shape: "-",
    attribute: "none",
    race: "none",
    set: "idol",
    acquire: "《偶像女團》活動期間",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "延1秒\n進場CD-2\n開技_自攻1.5倍",
    leader: ""
  },
  {
    name: "破影魔刀",
    num: "7157-7163",
    shape: "-",
    attribute: "light",
    race: "none",
    set: "none",
    acquire: "使用「魔滅・一願」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消8粒_自攻2倍\n魔1.05倍攻擊",
    leader: ""
  },
  {
    name: "聖光齒輪",
    num: "7150-7156",
    shape: "-",
    attribute: "dark",
    race: "none",
    set: "none",
    acquire: "使用「神創・零覓」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消5種符石_自攻2倍\n神1.05倍生命",
    leader: ""
  },
  {
    name: "雙魂法杖",
    num: "7140-7146",
    shape: "-",
    attribute: "wood",
    race: "none",
    set: "none",
    acquire: "使用「極限魔祭・司路域」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消3種符石_自攻1.5倍\n若人_自血1.15倍",
    leader: ""
  },
  {
    name: "藍影戰刀",
    num: "7122-7128",
    shape: "-",
    attribute: "water",
    race: "none",
    set: "none",
    acquire: "使用「獸道征途・凱撒」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消15粒獸_自攻1.1倍\n若獸_自血1.15倍",
    leader: ""
  },
  {
    name: "情牽水瓢",
    num: "7115-7121",
    shape: "-",
    attribute: "wood",
    race: "none",
    set: "none",
    acquire: "使用「染香綺狐・妲己」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消25粒_自攻1.6倍\n若妖_自血1.15倍",
    leader: ""
  },
  {
    name: "蒼藍靈心",
    num: "7082-7088",
    shape: "-",
    attribute: "water",
    race: "none",
    set: "none",
    acquire: "使用「最初的仿魂・莉莉絲」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "10/10/10",
    skill: "必延1秒\n消8粒_自攻2倍\n機攻1.05倍",
    leader: ""
  },
  {
    name: "朱纓燈",
    num: "7068-7074",
    shape: "-",
    attribute: "fire",
    race: "none",
    set: "none",
    acquire: "使用「天道炎旌・刻琿」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消15粒龍_自攻1.1倍\n若龍_自血1.1倍",
    leader: ""
  },
  {
    name: "神威之槍",
    num: "7059-7065",
    shape: "-",
    attribute: "light",
    race: "none",
    set: "none",
    acquire: "使用「環光聖戰・涅索伊」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消光3粒_自攻1.2倍\n若神_自攻1.2倍",
    leader: ""
  },
  {
    name: "秘術土偶",
    num: "7050-7056",
    shape: "-",
    attribute: "dark",
    race: "none",
    set: "none",
    acquire: "使用「朔月帝女・卑彌呼」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n進場CD-1\n若人自身生命力1.15倍",
    leader: ""
  },
  {
    name: "水色邀請函",
    num: "7164",
    shape: "-",
    attribute: "water",
    race: "none",
    set: "none",
    acquire: "使用「召喚師候選者」與「芸芸眾生」系列進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "開技_自攻1.5倍\n消3種符石_自攻1.5倍",
    leader: ""
  },
  {
    name: "赤色邀請函",
    num: "7165",
    shape: "-",
    attribute: "fire",
    race: "none",
    set: "none",
    acquire: "使用「召喚師候選者」與「芸芸眾生」系列進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "開技_自攻1.5倍\n消3種符石_自攻1.5倍",
    leader: ""
  },
  {
    name: "蒼色邀請函",
    num: "7166",
    shape: "-",
    attribute: "wood",
    race: "none",
    set: "none",
    acquire: "使用「召喚師候選者」與「芸芸眾生」系列進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "開技_自攻1.5倍\n消3種符石_自攻1.5倍",
    leader: ""
  },
  {
    name: "亮色邀請函",
    num: "7167",
    shape: "-",
    attribute: "light",
    race: "none",
    set: "none",
    acquire: "使用「召喚師候選者」與「芸芸眾生」系列進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "開技_自攻1.5倍\n消3種符石_自攻1.5倍",
    leader: ""
  },
  {
    name: "夜色邀請函",
    num: "7168",
    shape: "-",
    attribute: "dark",
    race: "none",
    set: "none",
    acquire: "使用「召喚師候選者」與「芸芸眾生」系列進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "開技_自攻1.5倍\n消3種符石_自攻1.5倍",
    leader: ""
  },
  {
    name: "水漩戟",
    num: "7091",
    shape: "-",
    attribute: "water",
    race: "none",
    set: "none",
    acquire: "龍金屬封印",
    accumulate: "消除水符石",
    ability: "5/5/5",
    skill: "延1秒\n消同屬4粒_自攻1.15倍\n對火目標_自攻1.15倍",
    leader: ""
  },
  {
    name: "鑲炎刀",
    num: "7092",
    shape: "-",
    attribute: "fire",
    race: "none",
    set: "none",
    acquire: "龍金屬封印",
    accumulate: "消除火符石",
    ability: "5/5/5",
    skill: "延1秒\n消同屬4粒_自攻1.15倍\n對木目標_自攻1.15倍",
    leader: ""
  },
  {
    name: "青翠棍",
    num: "7093",
    shape: "-",
    attribute: "wood",
    race: "none",
    set: "none",
    acquire: "龍金屬封印",
    accumulate: "消除木符石",
    ability: "5/5/5",
    skill: "延1秒\n消同屬4粒_自攻1.15倍\n對水目標_自攻1.15倍",
    leader: ""
  },
  {
    name: "翼光盾",
    num: "7094",
    shape: "-",
    attribute: "light",
    race: "none",
    set: "none",
    acquire: "龍金屬封印",
    accumulate: "消除光符石",
    ability: "5/5/5",
    skill: "延1秒\n消同屬4粒_自攻1.15倍\n對暗目標_自攻1.15倍",
    leader: ""
  },
  {
    name: "暗雙劍",
    num: "7095",
    shape: "-",
    attribute: "dark",
    race: "none",
    set: "none",
    acquire: "龍金屬封印",
    accumulate: "消除暗符石",
    ability: "5/5/5",
    skill: "延1秒\n消同屬4粒_自攻1.15倍\n對光目標_自攻1.15倍",
    leader: ""
  },
  {
    name: "埼玉的英雄服",
    num: "7129-7135",
    shape: "-",
    attribute: "none",
    race: "human",
    set: "none",
    acquire: "使用「埼玉」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消30粒_自攻1.6倍\n若人_自攻1.1倍",
    leader: ""
  },
  {
    name: "金蛇刀",
    num: "7075-7081",
    shape: "-",
    attribute: "none",
    race: "demon",
    set: "none",
    acquire: "使用「魔權在握・巴力」或「瀾漫勾惑・夏娃」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/10/10",
    skill: "必延1秒\n消魔_自攻1.15倍\n若魔_自血1.15倍",
    leader: ""
  },
  {
    name: "重械核",
    num: "3661-3667",
    shape: "-",
    attribute: "none",
    race: "machine",
    set: "none",
    acquire: "使用「異變．夏馬西」進行熔爐",
    accumulate: "",
    ability: "0/0/0",
    skill: "無視腐化",
    leader: ""
  },
  {
    name: "纖端核",
    num: "3654-3660",
    shape: "-",
    attribute: "none",
    race: "god",
    set: "none",
    acquire: "使用「異變．卡俄斯」進行熔爐",
    accumulate: "",
    ability: "0/0/0",
    skill: "無視腐化",
    leader: ""
  },
  {
    name: "蠹生核",
    num: "3647-3653",
    shape: "-",
    attribute: "none",
    race: "demon",
    set: "none",
    acquire: "使用「維度粉碎・猶格索托斯」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "0/10/10",
    skill: "延8秒\n消5種符石_自攻1.8倍\n無視腐化",
    leader: ""
  },
  {
    name: "卷鬚核",
    num: "3640-3646",
    shape: "-",
    attribute: "none",
    race: "god",
    set: "none",
    acquire: "使用「常世否定・姬氏」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "5/5/10",
    skill: "延1秒\n進場CD-2\n無視腐化",
    leader: ""
  },
  {
    name: "羽翼核",
    num: "3633-3639",
    shape: "-",
    attribute: "none",
    race: "god",
    set: "none",
    acquire: "使用「存在質疑・路西法」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "消神_自攻1.5倍\n消光與暗_自攻1.5倍\n無視腐化",
    leader: ""
  },
  {
    name: "胞質核",
    num: "3626-3632",
    shape: "-",
    attribute: "none",
    race: "dragon",
    set: "none",
    acquire: "使用「生死剝離．尼德霍格」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "15/5/0",
    skill: "進場CD-2\n開技_自攻1.5倍\n無視腐化",
    leader: ""
  },
  {
    name: "融冰核",
    num: "3619-3625",
    shape: "-",
    attribute: "none",
    race: "fairy",
    set: "none",
    acquire: "使用「根源倒錯・迪亞布羅」進行熔爐",
    accumulate: "消除心符石",
    ability: "0/0/20",
    skill: "進場CD-2\n消5連心回1.8倍隊回的血\n無視腐化",
    leader: ""
  },
  {
    name: "晶綻核",
    num: "3612-3618",
    shape: "-",
    attribute: "none",
    race: "god",
    set: "none",
    acquire: "使用「理智失序・奧丁」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "5/10/5",
    skill: "開技_自攻1.5倍\n消5粒_自攻1.5倍\n無視腐化",
    leader: ""
  },
  {
    name: "雙生核",
    num: "3605-3611",
    shape: "-",
    attribute: "none",
    race: "beast",
    set: "none",
    acquire: "使用「日墜月落・噬日狼與喰月狼」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "10/10/0",
    skill: "進場CD-1\n消光暗_自攻1.5倍\n無視腐化",
    leader: ""
  },
  {
    name: "怨念核",
    num: "3598-3604",
    shape: "-",
    attribute: "none",
    race: "fairy",
    set: "none",
    acquire: "使用「野望滅絕・薩魯曼」進行熔爐",
    accumulate: "消除暗符石",
    ability: "0/5/15",
    skill: "延1秒\n消妖_自攻1.5倍\n無視腐化",
    leader: ""
  },
  {
    name: "愛恨時計",
    num: "9002",
    shape: "-",
    attribute: "none",
    race: "machine",
    set: "none",
    acquire: "《初音未來》合作期間",
    accumulate: "發動攻擊的次數",
    ability: "4/4/4",
    skill: "延0.5秒\n消3水機_自攻1.1倍\n消25粒_自攻1.39倍",
    leader: ""
  },
  {
    name: "結晶林檎",
    num: "9004",
    shape: "-",
    attribute: "none",
    race: "machine",
    set: "none",
    acquire: "《初音未來》合作期間",
    accumulate: "發動攻擊的次數",
    ability: "4/4/4",
    skill: "延0.5秒\n消10粒_自攻1.1倍\n消25粒_自攻1.39倍",
    leader: ""
  },
  {
    name: "雙生蝶飾",
    num: "9006",
    shape: "-",
    attribute: "none",
    race: "machine",
    set: "none",
    acquire: "《初音未來》合作期間",
    accumulate: "發動攻擊的次數",
    ability: "4/4/4",
    skill: "延0.5秒\n消6連光_機攻1.2倍\n消25粒_自攻1.39倍",
    leader: ""
  },
  {
    name: "桃花雛偶",
    num: "7245-7251",
    shape: "-",
    attribute: "none",
    race: "god",
    set: "none",
    acquire: "桃花糕商店",
    accumulate: "連擊 4 或以上",
    ability: "5/5/5",
    skill: "進場CD-2\n消神_自攻1.5倍",
    leader: ""
  },
  {
    name: "漫花琉璃",
    num: "7169-7175",
    shape: "-",
    attribute: "none",
    race: "human",
    set: "none",
    acquire: "通過指定地域探索層數｜境外探索",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "消人_自攻1.15倍\n消人-人攻1.1倍",
    leader: ""
  },
  {
    name: "奪冠花劍",
    num: "9009",
    shape: "-",
    attribute: "none",
    race: "human",
    set: "none",
    acquire: "港隊奧運奪金贈送",
    accumulate: "消除任何符石",
    ability: "2/2/2",
    skill: "開技_自攻1.1倍\n消15粒_自攻1.1倍",
    leader: ""
  },
  {
    name: "幻之弦琴",
    num: "7001-7007",
    shape: "-",
    attribute: "none",
    race: "human",
    set: "none",
    acquire: "龍紋：眾神紀錄・主線 第十六章｜魔導紀元\n龍印：殺戮戰窟｜十封－存音石碑獎勵\n龍咒：祭祀遺址｜十封－存音石碑獎勵",
    accumulate: "消除任何符石",
    ability: "0/5/5",
    skill: "進場CD-1\n消25粒_自攻1.2倍",
    leader: ""
  },
  {
    name: "骨之凶笛",
    num: "7008-7014",
    shape: "-",
    attribute: "none",
    race: "beast",
    set: "none",
    acquire: "龍紋：魔法閣挑戰函 Extra｜十一封\n龍印：第一章｜旅人的記憶－邪馬台國傳說\n龍咒：第四章｜旅人的記憶－邪馬台國傳說",
    accumulate: "消除任何符石",
    ability: "5/5/0",
    skill: "延1秒\n消20粒_自攻1.15倍",
    leader: ""
  },
  {
    name: "靈之蓬簫",
    num: "7015-7021",
    shape: "-",
    attribute: "none",
    race: "fairy",
    set: "none",
    acquire: "龍紋：不安份影子｜旅人的記憶－新生跡印\n龍印：膨脹的支配｜旅人的記憶－新生跡印\n龍咒：第五章｜旅人的記憶－邪馬台國傳說",
    accumulate: "消除心符石",
    ability: "0/0/10",
    skill: "進場CD-1\n進場CD-1",
    leader: ""
  },
  {
    name: "遙之赤琴",
    num: "7022-7028",
    shape: "-",
    attribute: "none",
    race: "dragon",
    set: "none",
    acquire: "龍紋：美夢之下｜旅人的記憶－星辰封印\n龍印：踏進末日｜旅人的記憶－星辰封印\n龍咒：第二章｜旅人的記憶－邪馬台國傳說",
    accumulate: "消除任何符石",
    ability: "5/5/0",
    skill: "延1秒\n消20粒_自攻1.1倍",
    leader: ""
  },
  {
    name: "聖翼之鈴",
    num: "7029-7035",
    shape: "-",
    attribute: "none",
    race: "god",
    set: "none",
    acquire: "龍咒：眾神紀錄・絕望之末｜魔導紀元\n龍符：眾神紀錄・惡夢夜幕｜魔導紀元",
    accumulate: "消除任何符石",
    ability: "5/0/5",
    skill: "進場CD-1\n消15粒_自攻1.1倍",
    leader: ""
  },
  {
    name: "骷髏魔號",
    num: "7036-7042",
    shape: "-",
    attribute: "none",
    race: "demon",
    set: "none",
    acquire: "龍紋：永恆之牢｜十封－存音石碑獎勵\n龍符：迷城入口｜十封－存音石碑獎勵",
    accumulate: "消除任何符石",
    ability: "0/5/5",
    skill: "消3連心魔族_自攻1.1倍\n消20粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "動之輪鈸",
    num: "7043-7049",
    shape: "-",
    attribute: "none",
    race: "machine",
    set: "none",
    acquire: "龍紋：魔魅之軍的行進｜十一封\n龍印：第三章｜旅人的記憶－邪馬台國傳說",
    accumulate: "連擊 4 或以上",
    ability: "5/0/5",
    skill: "開技_自攻1.25倍\n消25粒_自攻1.1倍",
    leader: ""
  },
  {
    name: "神境光槍",
    num: "3591-3597",
    shape: "-",
    attribute: "light",
    race: "god",
    set: "Molin",
    acquire: "使用「神境旅塔．莫靈」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "CD-2\n消神_神攻1.15倍",
    leader: ""
  },
  {
    name: "石中羽",
    num: "3472-3478",
    shape: "-",
    attribute: "water",
    race: "dragon",
    set: "CangBi",
    acquire: "被審判的罪名、革命的狼煙｜旅人的記憶－代偶記事",
    accumulate: "受到攻擊次數",
    ability: "0/10/10",
    skill: "消直3水EP+1\n消3水_自攻1.25倍\n消6連水_自攻2.25倍",
    leader: ""
  },
  {
    name: "冒險書",
    num: "3465-3471",
    shape: "-",
    attribute: "water",
    race: "human",
    set: "Matthew",
    acquire: "「尋夢人．馬休」潛能解放",
    accumulate: "消除任何符石",
    ability: "5/5/5",
    skill: "必延1秒\n消3連心回1.5倍隊回的血\n開技_自攻1.5倍",
    leader: ""
  },
  {
    name: "勝利之劍",
    num: "3948-3954",
    shape: "-",
    attribute: "water",
    race: "god",
    set: "nordic",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "CD-1\n消5連水_自攻2.2倍\n消神_自攻1.5倍",
    leader: ""
  },
  {
    name: "煌耀戰刃",
    num: "3955-3961",
    shape: "-",
    attribute: "fire",
    race: "god",
    set: "nordic",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "CD-1\n消5連火_自攻2.2倍\n消神_自攻1.5倍",
    leader: ""
  },
  {
    name: "藤誓靈盾",
    num: "3962-3968",
    shape: "-",
    attribute: "wood",
    race: "god",
    set: "nordic",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "CD-1\n消5連木_自攻2.2倍\n消神_自攻1.5倍",
    leader: ""
  },
  {
    name: "召雷神槌",
    num: "3969-3975",
    shape: "-",
    attribute: "light",
    race: "god",
    set: "nordic",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "CD-1\n消5連光_自攻2.2倍\n消神_自攻1.5倍",
    leader: ""
  },
  {
    name: "邪惑匕首",
    num: "3976-3982",
    shape: "-",
    attribute: "dark",
    race: "god",
    set: "nordic",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "CD-1\n消5連暗_自攻2.2倍\n消神_自攻1.5倍",
    leader: ""
  },
  {
    name: "羽蛇盔",
    num: "3752-3758",
    shape: "-",
    attribute: "water",
    race: "dragon",
    set: "ancient",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/10/0",
    skill: "消水心_自攻1.5倍\n消龍_自攻1.5倍",
    leader: ""
  },
  {
    name: "焚項圈",
    num: "3759-3765",
    shape: "-",
    attribute: "fire",
    race: "dragon",
    set: "ancient",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/10/0",
    skill: "消火心_自攻1.5倍\n消龍_自攻1.5倍",
    leader: ""
  },
  {
    name: "靈寶晶",
    num: "3766-3772",
    shape: "-",
    attribute: "wood",
    race: "dragon",
    set: "ancient",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/10/0",
    skill: "消木心_自攻1.5倍\n消龍_自攻1.5倍",
    leader: ""
  },
  {
    name: "伐光藤",
    num: "3773-3779",
    shape: "-",
    attribute: "light",
    race: "dragon",
    set: "ancient",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/10/0",
    skill: "消光心_自攻1.5倍\n消龍_自攻1.5倍",
    leader: ""
  },
  {
    name: "龍霸爪",
    num: "3780-3786",
    shape: "-",
    attribute: "dark",
    race: "dragon",
    set: "ancient",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "5/10/0",
    skill: "消暗心_自攻1.5倍\n消龍_自攻1.5倍",
    leader: ""
  },
  {
    name: "時空沙漏",
    num: "3675-3681",
    shape: "-",
    attribute: "none",
    race: "none",
    set: "timeGate",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "10/0/10",
    skill: "必延1秒\n進場CD-3\n消5粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "水雲魔刺",
    num: "3430-3436",
    shape: "-",
    attribute: "water",
    race: "demon",
    set: "grace",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "0/15/0",
    skill: "對火目標_自攻1.5倍\n消3水_自攻1.25倍\n消20粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "灼熱魔刃",
    num: "3437-3443",
    shape: "-",
    attribute: "fire",
    race: "demon",
    set: "grace",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "0/15/0",
    skill: "對木目標_自攻1.5倍\n消3火_自攻1.25倍\n消20粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "靈木魔燭",
    num: "3444-3450",
    shape: "-",
    attribute: "wood",
    race: "demon",
    set: "grace",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "0/15/0",
    skill: "對水目標_自攻1.5倍\n消3木_自攻1.25倍\n消20粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "聖緞魔匕",
    num: "3451-3457",
    shape: "-",
    attribute: "light",
    race: "demon",
    set: "grace",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "0/15/0",
    skill: "對暗目標_自攻1.5倍\n消3光_自攻1.25倍\n消20粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "惡靈魔鐮",
    num: "3458-3464",
    shape: "-",
    attribute: "dark",
    race: "demon",
    set: "grace",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "0/15/0",
    skill: "對光目標_自攻1.5倍\n消3暗_自攻1.25倍\n消20粒_自攻1.5倍",
    leader: ""
  },
  {
    name: "絮飄法棒",
    num: "3360-3366",
    shape: "-",
    attribute: "water",
    race: "human",
    set: "witch",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "0/5/5",
    skill: "消20粒_自攻1.5倍\n對火目標_自攻1.5倍",
    leader: ""
  },
  {
    name: "閃灼法棒",
    num: "3367-3373",
    shape: "-",
    attribute: "fire",
    race: "human",
    set: "witch",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "0/5/5",
    skill: "消20粒_自攻1.5倍\n對木目標_自攻1.5倍",
    leader: ""
  },
  {
    name: "翠耀法棒",
    num: "3374-3380",
    shape: "-",
    attribute: "wood",
    race: "human",
    set: "witch",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "0/5/5",
    skill: "消20粒_自攻1.5倍\n對水目標_自攻1.5倍",
    leader: ""
  },
  {
    name: "獨眼盾",
    num: "3276-3282",
    shape: "-",
    attribute: "water",
    race: "beast",
    set: "warcraft",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除心符石",
    ability: "10/10/0",
    skill: "消4連心_自攻1.5倍\nCD-1",
    leader: ""
  },
  {
    name: "三犬頭戒",
    num: "3283-3284",
    shape: "-",
    attribute: "fire",
    race: "beast",
    set: "warcraft",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除火符石",
    ability: "10/10/0",
    skill: "消4火_自攻1.5倍\nCD-1",
    leader: ""
  },
  {
    name: "蛇首項鍊",
    num: "3290-3296",
    shape: "-",
    attribute: "wood",
    race: "beast",
    set: "warcraft",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "連擊 4 或以上",
    ability: "10/10/0",
    skill: "延1秒\n消直4木CD-1",
    leader: ""
  },
  {
    name: "鷲翼臂章",
    num: "3297-3303",
    shape: "-",
    attribute: "light",
    race: "beast",
    set: "warcraft",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除心符石",
    ability: "10/10/0",
    skill: "消4連心_自攻1.5倍\nCD-1",
    leader: ""
  },
  {
    name: "羊骨杯",
    num: "3304-3310",
    shape: "-",
    attribute: "dark",
    race: "beast",
    set: "warcraft",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除暗符石",
    ability: "10/10/0",
    skill: "消4暗_自攻1.5倍\nCD-1",
    leader: ""
  },
  {
    name: "龍首戰戈",
    num: "3241-3247",
    shape: "-",
    attribute: "water",
    race: "beast",
    set: "chineseBeasts",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "10/10/0",
    skill: "對火目標_自攻1.2倍\n開技_水攻1.15倍",
    leader: ""
  },
  {
    name: "赤翼法杖",
    num: "3248-3254",
    shape: "-",
    attribute: "fire",
    race: "beast",
    set: "chineseBeasts",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "10/10/0",
    skill: "對木目標_自攻1.2倍\n開技_火攻1.15倍",
    leader: ""
  },
  {
    name: "玄獸武刃",
    num: "3255-3261",
    shape: "-",
    attribute: "wood",
    race: "beast",
    set: "chineseBeasts",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "10/10/0",
    skill: "對水目標_自攻1.2倍\n開技_木攻1.15倍",
    leader: ""
  },
  {
    name: "白虎牙刀",
    num: "3262-3268",
    shape: "-",
    attribute: "light",
    race: "beast",
    set: "chineseBeasts",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "10/10/0",
    skill: "對暗目標_自攻1.2倍\n開技_光攻1.15倍",
    leader: ""
  },
  {
    name: "餮影重錘",
    num: "3269-3275",
    shape: "-",
    attribute: "dark",
    race: "beast",
    set: "chineseBeasts",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "發動攻擊的次數",
    ability: "10/10/0",
    skill: "對光目標_自攻1.2倍\n開技_暗攻1.15倍",
    leader: ""
  },
  {
    name: "皇祐水盾",
    num: "3156-3160, 3231, 3232",
    shape: "-",
    attribute: "water",
    race: "human",
    set: "ranger",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "延1秒\n消15粒_自攻2.2倍",
    leader: ""
  },
  {
    name: "熾焱巨斧",
    num: "3161-3165, 3233, 3234",
    shape: "-",
    attribute: "fire",
    race: "human",
    set: "ranger",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "延1秒\n消15粒_自攻2.2倍",
    leader: ""
  },
  {
    name: "悠古弓箭",
    num: "3166-3170, 3235, 3236",
    shape: "-",
    attribute: "wood",
    race: "human",
    set: "ranger",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "延1秒\n消15粒_自攻2.2倍",
    leader: ""
  },
  {
    name: "聖耀長槍",
    num: "3171-3175, 3237, 3238",
    shape: "-",
    attribute: "light",
    race: "human",
    set: "ranger",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "延1秒\n消15粒_自攻2.2倍",
    leader: ""
  },
  {
    name: "暗影邪刀",
    num: "3176-3180, 3239, 3240",
    shape: "-",
    attribute: "dark",
    race: "human",
    set: "ranger",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "延1秒\n消15粒_自攻2.2倍",
    leader: ""
  },
  {
    name: "天津法杖",
    num: "3131-3135, 3221, 3222",
    shape: "-",
    attribute: "water",
    race: "beast",
    set: "egyptian",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除水符石",
    ability: "10/10/0",
    skill: "木傷減10%\n開技_水攻1.15倍",
    leader: ""
  },
  {
    name: "公允之杖",
    num: "3136-3140, 3223, 3224",
    shape: "-",
    attribute: "fire",
    race: "dragon",
    set: "egyptian",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除火符石",
    ability: "10/10/0",
    skill: "水傷減10%\n開技_火攻1.15倍",
    leader: ""
  },
  {
    name: "颶風吊飾",
    num: "3141-3145, 3225, 3226",
    shape: "-",
    attribute: "wood",
    race: "dragon",
    set: "egyptian",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除木符石",
    ability: "10/10/0",
    skill: "火傷減10%\n開技_木攻1.15倍",
    leader: ""
  },
  {
    name: "日環鑰匙",
    num: "3146-3150, 3227, 3228",
    shape: "-",
    attribute: "light",
    race: "beast",
    set: "egyptian",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除光符石",
    ability: "10/10/0",
    skill: "暗傷減10%\n開技_光攻1.15倍",
    leader: ""
  },
  {
    name: "冥界寶杖",
    num: "3151-3155, 3229, 3230",
    shape: "-",
    attribute: "dark",
    race: "god",
    set: "egyptian",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除暗符石",
    ability: "10/10/0",
    skill: "光傷減10%\n開技_暗攻1.15倍",
    leader: ""
  },
  {
    name: "天鵝指環",
    num: "3106-3110, 3211, 3212",
    shape: "-",
    attribute: "water",
    race: "god",
    set: "destiny",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "消5連水_神攻1.2倍\n消4連心回1.5倍隊回的血",
    leader: ""
  },
  {
    name: "終結剪刀",
    num: "3111-3115, 3213, 3214",
    shape: "-",
    attribute: "fire",
    race: "god",
    set: "destiny",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "消5連火_神攻1.2倍\n消4連心回1.5倍隊回的血",
    leader: ""
  },
  {
    name: "命運紗線",
    num: "3116-3120, 3215, 3216",
    shape: "-",
    attribute: "wood",
    race: "god",
    set: "destiny",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "消5連木_神攻1.2倍\n消4連心回1.5倍隊回的血",
    leader: ""
  },
  {
    name: "永生聖果",
    num: "3121-3125, 3217, 3218",
    shape: "-",
    attribute: "light",
    race: "god",
    set: "destiny",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "消5連光_神攻1.2倍\n消4連心回1.5倍隊回的血",
    leader: ""
  },
  {
    name: "狩魂鐮刀",
    num: "3126-3130, 3219, 3220",
    shape: "-",
    attribute: "dark",
    race: "god",
    set: "destiny",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除任何符石",
    ability: "10/0/10",
    skill: "消5連暗_神攻1.2倍\n消4連心回1.5倍隊回的血",
    leader: ""
  },
  {
    name: "龍王劍",
    num: "3081-3085, 3201, 3202",
    shape: "-",
    attribute: "water",
    race: "dragon",
    set: "westJourney",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除水符石",
    ability: "10/10/10",
    skill: "延1秒\nCD-1\n開技_水攻1.15倍",
    leader: ""
  },
  {
    name: "風火輪",
    num: "3086-3090, 3203, 3204",
    shape: "-",
    attribute: "fire",
    race: "human",
    set: "westJourney",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除火符石",
    ability: "10/10/10",
    skill: "延1秒\nCD-1\n開技_火攻1.15倍",
    leader: ""
  },
  {
    name: "大力鎚",
    num: "3091-3095, 3205, 3206",
    shape: "-",
    attribute: "wood",
    race: "beast",
    set: "westJourney",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除木符石",
    ability: "10/10/10",
    skill: "延1秒\nCD-1\n開技_木攻1.15倍",
    leader: ""
  },
  {
    name: "如意棒",
    num: "3096-3100, 3207, 3208",
    shape: "-",
    attribute: "light",
    race: "god",
    set: "westJourney",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除光符石",
    ability: "10/10/10",
    skill: "延1秒\nCD-1\n開技_光攻1.15倍",
    leader: ""
  },
  {
    name: "妖羽扇",
    num: "3101-3105, 3209, 3210",
    shape: "-",
    attribute: "dark",
    race: "fairy",
    set: "westJourney",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除暗符石",
    ability: "10/10/10",
    skill: "延1秒\nCD-1\n開技_暗攻1.15倍",
    leader: ""
  },
  {
    name: "水龍扇",
    num: "3056-3060, 3191, 3192",
    shape: "-",
    attribute: "water",
    race: "dragon",
    set: "servant",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消連擊 4 或以上",
    ability: "10/10/0",
    skill: "進場CD-3\n消6連水_龍攻1.15倍",
    leader: ""
  },
  {
    name: "火龍雙刀",
    num: "3061-3065, 3193, 3194",
    shape: "-",
    attribute: "fire",
    race: "dragon",
    set: "servant",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消連擊 4 或以上",
    ability: "10/10/0",
    skill: "進場CD-3\n消6連火_龍攻1.15倍",
    leader: ""
  },
  {
    name: "木龍法杖",
    num: "3066-3070, 3195, 3196",
    shape: "-",
    attribute: "wood",
    race: "dragon",
    set: "servant",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消連擊 4 或以上",
    ability: "10/10/0",
    skill: "進場CD-3\n消6連木_龍攻1.15倍",
    leader: ""
  },
  {
    name: "光龍劍",
    num: "3071-3075, 3197, 3198",
    shape: "-",
    attribute: "light",
    race: "dragon",
    set: "servant",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消連擊 4 或以上",
    ability: "10/10/0",
    skill: "進場CD-3\n消6連光_龍攻1.15倍",
    leader: ""
  },
  {
    name: "暗龍弓",
    num: "3076-3080, 3199, 3200",
    shape: "-",
    attribute: "dark",
    race: "dragon",
    set: "servant",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消連擊 4 或以上",
    ability: "10/10/0",
    skill: "進場CD-3\n消6連暗_龍攻1.15倍",
    leader: ""
  },
  {
    name: "水刀",
    num: "3031-3035, 3181, 3182",
    shape: "-",
    attribute: "water",
    race: "human",
    set: "protagonist",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除水符石",
    ability: "0/10/10",
    skill: "CD-1\n消20粒_自攻2倍",
    leader: ""
  },
  {
    name: "火刃",
    num: "3036-3040, 3183, 3184",
    shape: "-",
    attribute: "fire",
    race: "human",
    set: "protagonist",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除火符石",
    ability: "0/10/10",
    skill: "CD-1\n消20粒_自攻2倍",
    leader: ""
  },
  {
    name: "獸角",
    num: "3041-3045, 3185, 3186",
    shape: "-",
    attribute: "wood",
    race: "human",
    set: "protagonist",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除木符石",
    ability: "0/10/10",
    skill: "CD-1\n消20粒_自攻2倍",
    leader: ""
  },
  {
    name: "銀鱗劍",
    num: "3046-3050, 3187, 3188",
    shape: "-",
    attribute: "light",
    race: "human",
    set: "protagonist",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除光符石",
    ability: "0/10/10",
    skill: "CD-1\n消20粒_自攻2倍",
    leader: ""
  },
  {
    name: "冥籠珠",
    num: "3051-3055, 3189, 3190",
    shape: "-",
    attribute: "dark",
    race: "human",
    set: "protagonist",
    acquire: "使用「對應角色」進行熔爐",
    accumulate: "消除暗符石",
    ability: "0/10/10",
    skill: "CD-1\n消20粒_自攻2倍",
    leader: ""
  },
  {
    name: "週年蛋糕",
    num: "9012",
    shape: "龍弦",
    attribute: "none",
    race: "none",
    set: "none",
    acquire: "週年贈送",
    accumulate: "消除任何符石",
    ability: "4/4/4",
    skill: "必延1秒\n進場CD-1",
    leader: ""
  },
  {
    name: "週年蛋糕",
    num: "9011",
    shape: "龍璃",
    attribute: "none",
    race: "none",
    set: "none",
    acquire: "週年贈送",
    accumulate: "消除任何符石",
    ability: "3/3/3",
    skill: "延1秒\n進場CD-1",
    leader: ""
  },
  {
    name: "週年蛋糕",
    num: "9008",
    shape: "龍丸",
    attribute: "none",
    race: "none",
    set: "none",
    acquire: "週年贈送",
    accumulate: "消除任何符石",
    ability: "1/1/1",
    skill: "延1秒\n進場CD-1",
    leader: ""
  },
  {
    name: "週年蛋糕",
    num: "9007",
    shape: "龍弦",
    attribute: "none",
    race: "none",
    set: "none",
    acquire: "週年贈送",
    accumulate: "消除任何符石",
    ability: "1/1/1",
    skill: "延1秒\n進場CD-1",
    leader: ""
  },
  {
    name: "章魚丸",
    num: "9010",
    shape: "龍印",
    attribute: "none",
    race: "none",
    set: "none",
    acquire: "神魔學園祭",
    accumulate: "消除任何符石",
    ability: "1/1/1",
    skill: "延1秒\n消4連心回1.5倍隊回的血",
    leader: ""
  },
];